# Índices dos landmarks e constantes de configuração
OMBRO_ESQUERDO = 11
OMBRO_DIREITO = 12
PULSO_ESQUERDO = 15
PULSO_DIREITO = 16
QUADRIL_ESQUERDO = 23
QUADRIL_DIREITO = 24
TORNOZELO_ESQUERDO = 27
TORNOZELO_DIREITO = 28

CONFIANCA_MIN_DETECCAO = 0.5
CONFIANCA_MIN_RASTREAMENTO = 0.5
RAZAO_TORNOZELO_QUADRIL_ABERTO = 1.5
RAZAO_TORNOZELO_QUADRIL_FECHADO = 1.25
MARGEM_BRACO_ACIMA_OMBRO = 0.05
MARGEM_PULSO_QUADRIL = 0.05
LIMITE_RAZAO_SIMETRIA = 2.5